# -*- coding: utf-8 -*-
"""trabalho algebra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bD7tRiL2QBMUBjUbQ75bAmWEgpDjMlwN
"""

# 0. Instalando e importando

!pip install kagglehub
import kagglehub
import pandas as pd
from kagglehub import KaggleDatasetAdapter
import numpy as np
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import sys

# --- ETAPA 1: CARREGAMENTO E PREPARAÇÃO DA BASE DE DADOS ---

KAGGLE_DATASET = "asaniczka/tmdb-movies-dataset-2023-930k-movies"
FILE_NAME = "TMDB_movie_dataset_v11.csv"
COLUMNS_TO_USE = ['title', 'overview', 'keywords', 'genres', 'tagline', 'vote_average', 'runtime', 'adult', 'release_date', 'original_language']

print(f"Tentando carregar o arquivo '{FILE_NAME}' do dataset '{KAGGLE_DATASET}'...")

try:
    # Usa pandas_kwargs para carregar SOMENTE as colunas necessárias
    df = kagglehub.load_dataset(
        KaggleDatasetAdapter.PANDAS,
        KAGGLE_DATASET,
        FILE_NAME,
        pandas_kwargs={'usecols': COLUMNS_TO_USE}
    )
    print("✅ Base de dados carregada com sucesso!")

except Exception as e:
    print(f"\nERRO FATAL ao carregar o dataset do Kaggle: {e}")
    sys.exit()

#corrigindo data pra ano de lançamento
df['release_year'] = pd.to_datetime(df['release_date'], errors='coerce').dt.year
df.dropna(subset=['release_year'], inplace=True)
df['release_year'] = df['release_year'].astype(int)

#filtros
df = df[(df['vote_average'] > 6.0) & (df['runtime'] > 60) & (df['adult'] == False) & (df['release_year'] >= 1995) & (df['original_language'] == 'en')].copy()

# Limpeza e Preparação do Texto
# 1. Trata valores nulos
df.fillna('', inplace=True)

# 2. Cria coluna combinada.
df['features'] = df['overview'] + ' ' + df['keywords'] + ' ' + df['genres'] + ' ' + df['tagline']

# Remove registros onde as features combinadas estão vazias após a limpeza
df_final = df[df['features'].str.strip() != ''].reset_index(drop=True)

#Dicionario
BASE_DE_FILMES = pd.Series(
    df_final['features'].values,
    index=df_final['title']
).to_dict()

print(f"Base de dados final pronta com {len(BASE_DE_FILMES)} títulos para análise.")

# --- PARTE DO ALGORITMO DE SIMILARIDADE ---

print("\n==============================================")
print("     🍿 INÍCIO DO SISTEMA DE RECOMENDAÇÃO DE FILMES 🎬")

# --- 1. COLETA DE DADOS INTERATIVA (APENAS QUERY) ---

print("\n--- ETAPA 1: DEFINIÇÃO DO PERFIL DE PREFERÊNCIA ---")
# MENSAGEM ATUALIZADA para FILMES
print("⚠ ATENÇÃO: Por favor, cole o texto que descreve os FILMES que você mais gosta, traduzido para o INGLÊS (Query).")

query_text = input("Query (English): ")

if not query_text.strip():
    print("ERRO: O texto da Query não pode ser vazio.")
    sys.exit()

# --- 2. PREPARAÇÃO DO CORPUS ---

# Corpus = [Query] + [Todos os Documentos de Filmes]
corpus = [query_text] + list(BASE_DE_FILMES.values())
nomes_documentos = list(BASE_DE_FILMES.keys())

# --- 3. VETORIZAÇÃO (TF-IDF) E PRÉ-PROCESSAMENTO ---

print("\n--- ETAPA 2: VETORIZAÇÃO TF-IDF ---")

# stop_words='english' e token_pattern=r'\b\w+\b' mantidos para compatibilidade com o dataset em inglês
vectorizer = TfidfVectorizer(
    stop_words='english',
    lowercase=True,
    token_pattern=r'\b\w+\b'
)

tfidf_matrix = vectorizer.fit_transform(corpus)

vetor_q = tfidf_matrix[0]
vetores_d = tfidf_matrix[1:]

# --- 4. CALCULAR ÂNGULOS (Similaridade de Cosseno) ---

similaridades_array = cosine_similarity(vetor_q, vetores_d)[0]
S_clip = np.clip(similaridades_array, -1.0, 1.0)
angulos_deg = np.degrees(np.arccos(S_clip))


# --- 5. CLASSIFICAR O MAIS SEMELHANTE ---

print("\n--- ETAPA 3: RANKING DE RECOMENDAÇÃO ---")

resultados_df = pd.DataFrame({
    'Filme': nomes_documentos,
    'Similaridade (S)': similaridades_array,
    'Ângulo (Graus)': angulos_deg
})

# Mostrar apenas o TOP 5
resultados_ordenados = resultados_df.sort_values(by='Similaridade (S)', ascending=False).reset_index(drop=True)
resultados_ordenados['Rank'] = resultados_ordenados.index + 1
top_5 = resultados_ordenados.head(5)

print("\nTOP 5 FILMES RECOMENDADOS (do Mais para o Menos Semelhante):\n")
print(top_5[['Rank', 'Filme', 'Similaridade (S)', 'Ângulo (Graus)']]) # Coluna renomeada

print("\nConclusão: A Similaridade de Cosseno (S) mede a proximidade semântica do título com o seu perfil.")